GeneralConfig:
  max-stack-size: 200
  keep-stacking: true
  kill-on-hit: true
  chunk-spawner-stacking: true



ItemConfig:
  general-name-format: '&8%type &7| &aTier %tier'
  lore:
    - '&7A Ultra Spawner!'
    - '&7Will spawn special mobs with custom drops!'
GuiConfig:
  fill-empty-slots: true
  filling-material: BLACK_STAINED_GLASS_PANE
  filling-name: '&7-'
  hologramStatus:
    enabled: 'enabled'
    disabled: 'disabled'
  type:
    material: SPAWNER
    name: '&a%type &8| &7Spawner'
    lore:
      - '&7The type of mob it will spawn'
  tier:
    material: DIAMOND
    name: '&a%tier &8| &7Tier'
    lore:
      - '&7This spawner tier level!'
      - '&7Each tier level will make the mobs drop something else!'
  stack:
    material: CHEST
    name: '&a%stack &8| &7Stack'
    lore:
      - '&7This many spawners are stacked inside this one'
  hologram:
    material: ARMOR_STAND
    name: '&a%hologramStatus &8| &7Hologram'
    lore:
      - '&7Click here to enable or disable the hologram!'
  upgrade:
    material: EXPERIENCE_BOTTLE
    name: '&aUpgrade'
    lore:
      - '&7This spawner can be upgraded to tier %nextTier'
      - '&7You can buy the upgrade for &a$%upgradeCost'
  maxUpgrade:
    material: EXPERIENCE_BOTTLE
    name: '&aMax Tier'
    lore:
      - '&7This spawner is at the highest tier'
      - '&7You can not upgrade it anymore!'